[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/web-mar_agrosoluciones.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
